# Generated by Django 5.1.5 on 2025-01-21 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.FloatField(blank=True, null=True)),
                ('literature', models.FloatField(blank=True, null=True)),
                ('english', models.FloatField(blank=True, null=True)),
                ('physics', models.FloatField(blank=True, null=True)),
                ('chemistry', models.FloatField(blank=True, null=True)),
                ('biology', models.FloatField(blank=True, null=True)),
                ('history', models.FloatField(blank=True, null=True)),
                ('geography', models.FloatField(blank=True, null=True)),
                ('civics', models.FloatField(blank=True, null=True)),
                ('foreign_language_code', models.CharField(blank=True, max_length=5, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='students.student')),
            ],
            options={
                'db_table': 'scores',
            },
        ),
    ]
