# Generated by Django 5.1.5 on 2025-01-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='english',
            new_name='language',
        ),
    ]
